#if !defined(AFX_MCD_H__5FA46B25_8DA6_4005_9FE4_873837BADBEE__INCLUDED_)
#define AFX_MCD_H__5FA46B25_8DA6_4005_9FE4_873837BADBEE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMcd wrapper class

class CMcd : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMcd)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5c3ee2fd, 0x5b12, 0x4de9, { 0xa6, 0x29, 0x64, 0x34, 0xd1, 0xc, 0x4c, 0x1b } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetDirection();
	void SetDirection(BOOL);

// Operations
public:
	void SetNumbers(long x, long y);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MCD_H__5FA46B25_8DA6_4005_9FE4_873837BADBEE__INCLUDED_)
